Repository Abir-Tx/EzWatchTicketing, pull requests merged in 2023-08, with the labels that each got.

#1 Create Employee service with basic API & Initialize the basic packages
  EWT/EWT-BLL/DTOs/EmployeeDTO.cs
  EWT/EWT-BLL/EWT-BLL.csproj
  EWT/EWT-BLL/Services/EmployeeService.cs
  EWT/EWT-BLL/packages.config
  EWT/EWT-DAL/DataAccesser.cs
  EWT/EWT-DAL/EF/EWTContext.cs
  EWT/EWT-DAL/EF/Models/Employee.cs
  EWT/EWT-DAL/EWT-DAL.csproj
  EWT/EWT-DAL/Interfaces/IRepo.cs
  EWT/EWT-DAL/Migrations/202308120806219_InitEmployee.Designer.cs
  EWT/EWT-DAL/Migrations/202308120806219_InitEmployee.cs
  EWT/EWT-DAL/Migrations/202308120806219_InitEmployee.resx
  EWT/EWT-DAL/Repos/EmployeeRepo.cs
  EWT/EWT-DAL/Repos/Repo.cs
  EWT/EWT-UI/App_Start/WebApiConfig.cs
  EWT/EWT-UI/Controllers/EmployeeController.cs
  EWT/EWT-UI/EWT-UI.csproj
  EWT/EWT-UI/packages.config
Labels: enhancement

#2 Addition of Movies entity and it's CRUD APIs
  EWT/EWT-BLL/DTOs/MovieDTO.cs
  EWT/EWT-BLL/EWT-BLL.csproj
  EWT/EWT-BLL/Services/EmployeeService.cs
  EWT/EWT-BLL/Services/MovieService.cs
  EWT/EWT-DAL/DataAccesser.cs
  EWT/EWT-DAL/EF/EWTContext.cs
  EWT/EWT-DAL/EF/Models/Movie.cs
  EWT/EWT-DAL/EWT-DAL.csproj
  EWT/EWT-DAL/Migrations/202308121638378_InitMovie.Designer.cs
  EWT/EWT-DAL/Migrations/202308121638378_InitMovie.cs
  EWT/EWT-DAL/Migrations/202308121638378_InitMovie.resx
  EWT/EWT-DAL/Repos/EmployeeRepo.cs
  EWT/EWT-DAL/Repos/MovieRepo.cs
  EWT/EWT-UI/Controllers/MovieController.cs
  EWT/EWT-UI/EWT-UI.csproj
Labels: enhancement

#3 Add complete CRUD APIs for Movie & Employee entities
  EWT/EWT-BLL/DTOs/MovieDTO.cs
  EWT/EWT-BLL/EWT-BLL.csproj
  EWT/EWT-BLL/Services/EmployeeService.cs
  EWT/EWT-BLL/Services/MovieService.cs
  EWT/EWT-DAL/DataAccesser.cs
  EWT/EWT-DAL/EF/EWTContext.cs
  EWT/EWT-DAL/EF/Models/Movie.cs
  EWT/EWT-DAL/EWT-DAL.csproj
  EWT/EWT-DAL/Migrations/202308121638378_InitMovie.Designer.cs
  EWT/EWT-DAL/Migrations/202308121638378_InitMovie.cs
  EWT/EWT-DAL/Migrations/202308121638378_InitMovie.resx
  EWT/EWT-DAL/Repos/EmployeeRepo.cs
  EWT/EWT-DAL/Repos/MovieRepo.cs
  EWT/EWT-UI/Controllers/EmployeeController.cs
  EWT/EWT-UI/Controllers/MovieController.cs
  EWT/EWT-UI/EWT-UI.csproj
Labels: enhancement

#5 Add Hall , Payment API
  EWT/EWT-BLL/DTOs/HallDTO.cs
  EWT/EWT-BLL/DTOs/HallSeatDTO.cs
  EWT/EWT-BLL/DTOs/PayMethodDTO.cs
  EWT/EWT-BLL/DTOs/PaymentDTO.cs
  EWT/EWT-BLL/DTOs/SeatDTO.cs
  EWT/EWT-BLL/EWT-BLL.csproj
  EWT/EWT-BLL/Services/HallService.cs
  EWT/EWT-BLL/Services/PaymentServices.cs
  EWT/EWT-DAL/DataAccesser.cs
  EWT/EWT-DAL/EF/EWTContext.cs
  EWT/EWT-DAL/EF/Models/Hall.cs
  EWT/EWT-DAL/EF/Models/PayMethod.cs
  EWT/EWT-DAL/EF/Models/Payment.cs
  EWT/EWT-DAL/EF/Models/Seat.cs
  EWT/EWT-DAL/EWT-DAL.csproj
  EWT/EWT-DAL/Interfaces/IRepo.cs
  EWT/EWT-DAL/Migrations/202308122110525_addHAll.Designer.cs
  EWT/EWT-DAL/Migrations/202308122110525_addHAll.cs
  EWT/EWT-DAL/Migrations/202308122110525_addHAll.resx
  EWT/EWT-DAL/Migrations/202308122150246_paymentAndSeatAdded.Designer.cs
  EWT/EWT-DAL/Migrations/202308122150246_paymentAndSeatAdded.cs
  EWT/EWT-DAL/Migrations/202308122150246_paymentAndSeatAdded.resx
  EWT/EWT-DAL/Migrations/202308130029423_payment_method_added.Designer.cs
  EWT/EWT-DAL/Migrations/202308130029423_payment_method_added.cs
  EWT/EWT-DAL/Migrations/202308130029423_payment_method_added.resx
  EWT/EWT-DAL/Repos/HallRepo.cs
  EWT/EWT-DAL/Repos/PaymentRepo.cs
  EWT/EWT-DAL/Repos/Repo.cs
  EWT/EWT-UI/Controllers/HallController.cs
  EWT/EWT-UI/Controllers/PaymentController.cs
  EWT/EWT-UI/EWT-UI.csproj
  EWT/EWT-UI/Web.config
  EWT/EWT-UI/packages.config
Labels: enhancement

#6 Add general user entity
  EWT/EWT-BLL/DTOs/UserDTO.cs
  EWT/EWT-BLL/EWT-BLL.csproj
  EWT/EWT-BLL/Services/Userservice.cs
  EWT/EWT-DAL/DataAccesser.cs
  EWT/EWT-DAL/EWT-DAL.csproj
  EWT/EWT-DAL/Repos/EmployeeRepo.cs
  EWT/EWT-DAL/Repos/IUserRepo.cs
  EWT/EWT-DAL/Repos/UserRepo.cs
  EWT/EWT-DAL/packages.config
  EWT/EWT-UI/Controllers/UserController.cs
  EWT/EWT-UI/EWT-UI.csproj
  EWT/EWT-UI/Web.config
Labels: enhancement

#9 [TDD] Add GitHub actions CI/CD for automatic building of the solution
  .github/workflows/build.yml
Labels: enhancement

#7 Merge all the entities from other contributors
  EWT/EWT-BLL/DTOs/HallDTO.cs
  EWT/EWT-BLL/DTOs/HallSeatDTO.cs
  EWT/EWT-BLL/DTOs/PayMethodDTO.cs
  EWT/EWT-BLL/DTOs/PaymentDTO.cs
  EWT/EWT-BLL/DTOs/SeatDTO.cs
  EWT/EWT-BLL/DTOs/UserDTO.cs
  EWT/EWT-BLL/EWT-BLL.csproj
  EWT/EWT-BLL/Properties/AssemblyInfo.cs
  EWT/EWT-BLL/Services/HallService.cs
  EWT/EWT-BLL/Services/PaymentServices.cs
  EWT/EWT-BLL/Services/Userservice.cs
  EWT/EWT-DAL/DataAccesser.cs
  EWT/EWT-DAL/EF/EWTContext.cs
  EWT/EWT-DAL/EF/Models/Hall.cs
  EWT/EWT-DAL/EF/Models/PayMethod.cs
  EWT/EWT-DAL/EF/Models/Payment.cs
  EWT/EWT-DAL/EF/Models/Seat.cs
  EWT/EWT-DAL/EWT-DAL.csproj
  EWT/EWT-DAL/Interfaces/IRepo.cs
  EWT/EWT-DAL/Migrations/202308122041435_MergeNelow.cs
  EWT/EWT-DAL/Migrations/202308122110525_addHAll.Designer.cs
  EWT/EWT-DAL/Migrations/202308122110525_addHAll.cs
  EWT/EWT-DAL/Migrations/202308122110525_addHAll.resx
  EWT/EWT-DAL/Migrations/202308122150246_paymentAndSeatAdded.Designer.cs
  EWT/EWT-DAL/Migrations/202308122150246_paymentAndSeatAdded.cs
  EWT/EWT-DAL/Migrations/202308122150246_paymentAndSeatAdded.resx
  EWT/EWT-DAL/Migrations/202308130029423_payment_method_added.Designer.cs
  EWT/EWT-DAL/Migrations/202308130029423_payment_method_added.cs
  EWT/EWT-DAL/Migrations/202308130029423_payment_method_added.resx
  EWT/EWT-DAL/Repos/EmployeeRepo.cs
  EWT/EWT-DAL/Repos/HallRepo.cs
  EWT/EWT-DAL/Repos/IUserRepo.cs
  EWT/EWT-DAL/Repos/PaymentRepo.cs
  EWT/EWT-DAL/Repos/Repo.cs
  EWT/EWT-DAL/Repos/UserRepo.cs
  EWT/EWT-DAL/packages.config
  EWT/EWT-UI/Controllers/HallController.cs
  EWT/EWT-UI/Controllers/HomeController.cs
  EWT/EWT-UI/Controllers/PaymentController.cs
  EWT/EWT-UI/Controllers/UserController.cs
  EWT/EWT-UI/EWT-UI.csproj
  EWT/EWT-UI/Web.config
  EWT/EWT-UI/packages.config
  webconfig
Labels: enhancement

#10 Add Employee authentication with base classes
  EWT/EWT-BLL/DTOs/TokenDTO.cs
  EWT/EWT-BLL/EWT-BLL.csproj
  EWT/EWT-BLL/Services/AuthService.cs
  EWT/EWT-DAL/DataAccesser.cs
  EWT/EWT-DAL/EF/EWTContext.cs
  EWT/EWT-DAL/EF/Models/Employee.cs
  EWT/EWT-DAL/EF/Models/Role.cs
  EWT/EWT-DAL/EF/Models/Token.cs
  EWT/EWT-DAL/EWT-DAL.csproj
  EWT/EWT-DAL/Interfaces/IAuth.cs
  EWT/EWT-DAL/Migrations/202308140646363_InitToken.Designer.cs
  EWT/EWT-DAL/Migrations/202308140646363_InitToken.cs
  EWT/EWT-DAL/Migrations/202308140646363_InitToken.resx
  EWT/EWT-DAL/Migrations/202308180554349_AddRolesToUsers.Designer.cs
  EWT/EWT-DAL/Migrations/202308180554349_AddRolesToUsers.cs
  EWT/EWT-DAL/Migrations/202308180554349_AddRolesToUsers.resx
  EWT/EWT-DAL/Migrations/202308180602311_AddRoleToEmp.Designer.cs
  EWT/EWT-DAL/Migrations/202308180602311_AddRoleToEmp.cs
  EWT/EWT-DAL/Migrations/202308180602311_AddRoleToEmp.resx
  EWT/EWT-DAL/Repos/EmployeeRepo.cs
  EWT/EWT-DAL/Repos/TokenRepo.cs
  EWT/EWT-UI/AuthFilters/EmployeeFilter.cs
  EWT/EWT-UI/AuthFilters/LoginFilter.cs
  EWT/EWT-UI/Controllers/EmployeeController.cs
  EWT/EWT-UI/EWT-UI.csproj
  EWT/EWT-UI/Models/LoginModel.cs
  EWT/EWT-UI/Web.config
Labels: enhancement

#11 [DOCUMENTATION] Add user & dev documentation 📝
  .github/images/EWT_API_Authentication_example.png
  README.md
  docs/README.md
  docs/devdoc.md
Labels: documentation

#14 Addition of feature APIs to the Employee User Route
  EWT/EWT-UI/Controllers/EmployeeController.cs
  EWT/EWT-UI/Controllers/MovieController.cs
  EWT/EWT-UI/Web.config
  docs/devdoc.md
Labels: enhancement

#12 Admin All Updated
  EWT/EWT-BLL/Services/AuthService.cs
  EWT/EWT-DAL/EF/Models/Admin.cs
  EWT/EWT-DAL/EWT-DAL.csproj
  EWT/EWT-DAL/Migrations/202308241841376_AddAdminRoleId.Designer.cs
  EWT/EWT-DAL/Migrations/202308241841376_AddAdminRoleId.cs
  EWT/EWT-DAL/Migrations/202308241841376_AddAdminRoleId.resx
  EWT/EWT-DAL/Repos/AdminRepo.cs
  EWT/EWT-UI/AuthFilters/AdminFilter.cs
  EWT/EWT-UI/Controllers/AdminController.cs
  EWT/EWT-UI/EWT-UI.csproj
  EWT/EWT-UI/Models/AdminDTO.cs
Labels: enhancement

#16 Add movie tickets relation and feature API's related to that
  EWT/EWT-BLL/Services/MovieService.cs
  EWT/EWT-DAL/EF/Models/Movie.cs
  EWT/EWT-DAL/EF/Models/Ticket.cs
  EWT/EWT-DAL/EWT-DAL.csproj
  EWT/EWT-DAL/Migrations/202308260942080_TicketMovieRelation.Designer.cs
  EWT/EWT-DAL/Migrations/202308260942080_TicketMovieRelation.cs
  EWT/EWT-DAL/Migrations/202308260942080_TicketMovieRelation.resx
  EWT/EWT-UI/Controllers/EmployeeController.cs
  EWT/EWT-UI/EWT-UI.csproj
  EWT/EWT-UI/Models/TicketDTO.cs
  docs/devdoc.md
Labels: enhancement

#13 Addition of the final API for General User
  EWT/EWT-BLL/DTOs/UserDTO.cs
  EWT/EWT-BLL/EWT-BLL.csproj
  EWT/EWT-BLL/Services/AuthService.cs
  EWT/EWT-BLL/Services/Userservice.cs
  EWT/EWT-DAL/EF/Models/User.cs
  EWT/EWT-DAL/EWT-DAL.csproj
  EWT/EWT-DAL/Migrations/202308280725470_Polish.Designer.cs
  EWT/EWT-DAL/Migrations/202308280725470_Polish.cs
  EWT/EWT-DAL/Migrations/202308280725470_Polish.resx
  EWT/EWT-DAL/Repos/UserRepo.cs
  EWT/EWT-UI/AuthFilters/UserFilter.cs
  EWT/EWT-UI/Controllers/UserController.cs
  EWT/EWT-UI/EWT-UI.csproj
  EWT/EWT-UI/Web.config
Labels: bug, enhancement

#17 Add general user related feature APIs to Emp endpoint
  EWT/EWT-BLL/DTOs/UserDTO.cs
  EWT/EWT-BLL/EWT-BLL.csproj
  EWT/EWT-BLL/Services/AuthService.cs
  EWT/EWT-BLL/Services/Userservice.cs
  EWT/EWT-DAL/EF/Models/User.cs
  EWT/EWT-DAL/EWT-DAL.csproj
  EWT/EWT-DAL/Migrations/202308280725470_Polish.Designer.cs
  EWT/EWT-DAL/Migrations/202308280725470_Polish.cs
  EWT/EWT-DAL/Migrations/202308280725470_Polish.resx
  EWT/EWT-DAL/Repos/UserRepo.cs
  EWT/EWT-UI/AuthFilters/UserFilter.cs
  EWT/EWT-UI/Controllers/EmployeeController.cs
  EWT/EWT-UI/Controllers/UserController.cs
  EWT/EWT-UI/EWT-UI.csproj
  EWT/EWT-UI/Web.config
Labels: bug, enhancement

#19 Add feature APIs for Admin Endpoint
  EWT/EWT-UI/Controllers/AdminController.cs
  EWT/EWT-UI/Web.config
Labels: enhancement
